"""add coordinates to matches

Revision ID: 23d2c57b7444
Revises: c41ebaec0829
Create Date: 2026-05-27 09:31:57.799051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23d2c57b7444'
down_revision: Union[str, Sequence[str], None] = 'c41ebaec0829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'longitude')
    op.drop_column('matches', 'latitude')
    # ### end Alembic commands ###
